### ISSUE TITLE
Uniform Code Style?

### ISSUE THREAD

**Issue by ukstv** [0xProject/web3-typescript-typings#4]
Uniform code style for the repo would make it easier to provide pull request consistent with existing code base.

Maybe you could standardise on https://standardjs.com based on already chosen single quotes.

**Comment by fabioberger** [comment]
Thanks for the suggestion @ukstv. I'd like to know what parts of the codebase you find inconsistent. Any examples?

**Comment by ukstv** [comment]
Would missing semicolon in another pull request fit the definition of an example? ;)
Nothing now *enforces* or explicitly declares code style, be it tslint, or eslint, or whatever.

**Comment by fabioberger** [comment]
That's a good point. I'll add tslint to this repo, we use it in all our other projects.

**Comment by LogvinovLeon** [comment]
I've added a tslint.json file to this repo and fixed all linter errors.
Use `npm run lint` or `yarn lint` to run the linter on new pr's
