### ISSUE TITLE
Inconsistent error type in callbacks

### ISSUE THREAD

**Issue by LibertyLocked** [0xProject/web3-typescript-typings#9]
Some callbacks have `err: any` and some callbacks have `err: Error`, there

e.g.

Here it's `any`
```typescript
getCode(addressHexString: string, callback?: (err: any, code: string) => void): string;
```

Here it's `Error`
```typescript
sign(address: string, message: string, callback: (err: Error, signData: string) => void): string;
```

Here it's `string|null` (in `interface FilterResult`)
```typescript
watch<A>(callback: (error: string|null, result: SolidityEvent<A>) => void): void;
```

Also some optional callbacks have the `?` missing, like the `sign()` above

**Comment by LogvinovLeon** [comment]
Addressed in latest master. Thx!
